config/routes.rb
Rails.application.routes.draw do

  root 'application#index'
  get '/about', :to => 'application#about'
  resources :comments
  resources :rewards
  resources :categories
  resources :projects
  devise_for :users

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true
  has_many :projects
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :title, :body, presence: true
  belongs_to :user
  belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, :user, :goal, presence: true
  belongs_to :user
  has_one :category
end

app/models/reward.rb
class Reward < ActiveRecord::Base
  validates :name, :value, presence: true
  belongs_to :project
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :projects
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def index
  end

  def about
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category
    else
      render :new
    end
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to @category
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def new
    @comment = Comment.new
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def create
    @comment = current_user.comments.build(comment_params)
    if @comment.save
      redirect_to @comment
    else
      render :new
    end
  end

  def update
    @comment = Comment.find(params[:id])

    if @comment.update(comment_params)
      redirect_to @comment
    else
      render :edit
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to comments_path
  end

  private
    def comment_params
      params.require(:comment).permit(:title, :body, :project_id)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :destroy, :update]

  def index
    @projects = current_user.projects.all
  end
  def new
    @project = Project.new
  end
  def edit
    @project = Project.find(params[:id])
  end
  def show
    @project = Project.find(params[:id])
  end
  def create
    @project = current_user.projects.build(project_params)
    if @project.save
      redirect_to @project
    else
      render :new
    end
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      redirect_to @project
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path
  end

  private
    def project_params
      params.require(:project).permit(:name, :description, :goal, :image, :video, :expiration_date, :category_id)
    end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  def index
    @rewards = Reward.all
  end
  def show
    @reward = Reward.find(params[:id])
  end

  def new
    @reward = Reward.new
  end

  def edit
    @reward = Reward.find(params[:id])
  end

  def create
    @reward = Reward.new(reward_params)
    if @reward.save
      redirect_to @reward
    else
      render :new
    end
  end

  def update
    @reward = Reward.find(params[:id])
    if @reward.update(reward_params)
      redirect_to @reward
    else
      render :edit
    end
  end

  def destroy
     @reward = Reward.find(params[:id])
     @reward.destroy
     redirect_to rewards_path
  end

  private
    def reward_params
      params.require(:reward).permit(:name, :value, :description, :project_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/views/application/about.html.slim
h1 About us

p
  | We are you!

p
  | Come and join us!

p
  | Bye!

app/views/application/index.html.slim
div class="gallery autoplay items-3"
  div id="item-1" class="control-operator"
  div id="item-2" class="control-operator"
  div id="item-3" class="control-operator"

  figure class="item"
    h1
      | First

  figure class="item"
    h1
      | Second

  figure class="item"
    h1
      | Third

  div class="controls"
    a href="#item-1" class="control-button"
      | •
    a href="#item-2" class="control-button"
      | •
    a href="#item-3" class="control-button"
      | •

div class="projects-display"
  div class="projects-top"
    h2 Popular
    button id="see-all-btn"
      | See all
  div class="projects-content"
    div class="project"
      div class="project-image"
        = image_tag("castle.jpg")
      div class="project-description"
        h3
          = link_to "Project Name", projects_path
        h5 @Creators
        div class="short-description"
          | This is a short descriptions of the project, lorem ipsum.
        br
        span class="city"
          i class="material-icons" room
          | Teresina, PI
        div class="meter"
          span style="width: 65%;" class="progress-bar"
        br
        div class="total-funded"
          p class="total-top"
            | 65%
          span class="total-bottom"
            | funded
        div class="total-goal"
          p class="total-top"
            | R$ 5.000,00
          span class="total-bottom"
            | pledge
        div class="total-days-left"
          p class="total-top"
            | 10
          span class="total-bottom"
            | days to go

app/views/categories/_form.html.slim
= form_for @category do |f|
  p
    = f.label :name
    = f.text_field :name

  = f.submit
end

app/views/categories/edit.html.slim
h1 Edit Category

= render 'form'

app/views/categories/index.html.slim
h1 Categories
= link_to "New Category", new_category_path
- if @categories
  - @categories.each do |category|
    p
      = category.name
      = link_to 'Edit', edit_category_path(category)
  end
end

app/views/categories/new.html.slim
h1 New Category

= render 'form'

app/views/categories/show.html.slim
p
  = @category.name

= link_to 'Edit', edit_category_path(@category)
= link_to 'Categories', categories_path

app/views/comments/_form.html.slim
= form_for @comment do |f|
  p
    = f.label :title
    = f.text_field :title

  p
    = f.label :body
    = f.text_area :body

  = f.submit
end

app/views/comments/edit.html.slim
h1 Edit Comment

= render 'form'

app/views/comments/index.html.slim
h1 Comments

= link_to 'New Comment', new_comment_path

- if @comments.any?
  - @comments.each do |comment|
    p
      = comment.user_id
      = comment.title
      = comment.body
      = comment.project_id
      = link_to 'More', comment_path(comment)
  end
- else
  p
    | No comments!
end

app/views/comments/new.html.slim
h1 New Comment

= render 'form'

app/views/comments/show.html.slim
p
  = @comment.title
p
  = @comment.body
p
  = @comment.user_id
p
  = @comment.project_id

= link_to 'Edit', edit_comment_path(@comment)
= link_to 'Comments', comments_path

app/views/layouts/application.html.slim
<!DOCTYPE html>
<html>
head
  title
    | Patrocina - A Crowdfunding application
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
body

  ul class="nav"
    li id="settings"
      = link_to 'Patrocina', root_path
    li
      a href="#"
        | Discover
    li
      a href="#"
        | Start Project
    li id="search"
      form action="" method="get"
        input type="text" name="search_text" id="search_text" placeholder="Search"
        input type="button" name="search_button" id="search_button"
    - if signed_in?
      li id="options"
        a href="#"
          | Options
          ul class="subnav"
            li
              = link_to 'Projects', projects_path
            li
              = link_to 'Sign out', destroy_user_session_path, method: :delete
    - else
      li id="signup"
        = link_to 'Sign up', new_user_registration_path
      li id="login"
        = link_to 'Login', new_user_session_path
  div classs="wrapper"
    = yield

  footer
    div class="footer-section-1"
      ul
        li class="footer-title" About us
        li What is Patrocina?
        li Who we are
        li Jobs
        li Newsletters
        li Github
    div class="footer-section-2"
      ul
        li class="footer-title" Help
        li FAQ
        li Our rules
        li Creator Handbook
        li Support
        li Terms of use
        li Privacy Policy
    div class="footer-section-3"
      ul
        li class="footer-title" Discover
        li Art
        li Games
        li Technology
    div class="footer-section-4"
      ul
        li class="footer-title" Hello
        li Blog
        li Engineering Blog
        li Twitter
        li Facebook
        li Instagram
        li Youtube

    div class="footer-section-5"
      ul
        li Patrocina
    div class="footer-section-6"
      ul
        li Language

app/views/projects/_form.html.slim
= form_for @project do |f|
  p
    = f.label :name
    = f.text_field :name

  p
    = f.label :description
    = f.text_field :description

  p
    = f.label :goal
    = f.number_field(:goal, in: 1.0..1000000.0, step: 0.5)

  p
    = f.label :image
    = f.text_field :image

  p
    = f.label :video
    = f.text_field :video

  = f.submit
end

app/views/projects/edit.html.slim
h1 Edit Project

= render 'form'

app/views/projects/index.html.slim
h1 My Projects
= link_to "New Project", new_project_path
- if @projects
  - @projects.each do |project|
    p
      = project.name
      = project.goal
      = link_to 'See', project_path(project)
  end
end

app/views/projects/new.html.slim
h2 New Project

= render 'form'

app/views/projects/show.html.slim
div class="show-project"
  - if current_user
    div class="user-control"
      - if @project.user_id == current_user.id
        = button_to 'Edit Project', edit_project_path(@project), method: :get
  div class="project-header"
    div class="project-top"
      div class="project-title"
        span
          = @project.name
        p
          | @Creators
      div class="project-data"
        = image_tag "html.jpg"
        p City, ST
        p = @project.description
        p Social Share

      div class="project-info"
        div class="show-badge"
          p 72
          span backers
        div class="show-badge"
          p R$ 5.000,00
          span pledged of
          = " R$ " + @project.goal.to_s
          |  goal
        div class="show-badge"
          p 35
          span days to go
        button id="back-btn" Back this project
        p id="disclaimer" This project will only be  founded if at least R$ 10.000,00 is pledged by Fri, May 20 2016 10:54 AM BRT.
        div class="founders"
          div class="founders-info"
            p Founders
            p class="small-text" 4 Created / 4 Backed
            p class="small-text" www.site.com.br
            p
              a href="#" See full bio
              a href="#"  Contact me
          div class="founders-logo"
            = image_tag("founders.jpg")
  div id="project-navbar" class="project-navbar"
    ul
      li
        a href="#campaign" class="tablink" onclick="openTab(event, 'campaign')" Campaign
      li
        a href="#updates" class="tablink" onclick="openTab(event, 'updates')"
          | Updates
          span 2
      li
        a href="#comments" class="tablink" onclick="openTab(event, 'comments')"
          | Comments
          span 2
      li
        a href="#backers" class="tablink" onclick="openTab(event, 'backers')"
          | Backers
          span 2
  div class="project-info-content"
    div id="campaign" class="campaign tabs"
      div class="project-campaign"
        p
          p
            | O projeto

          p
            | Pedimos a sua ajuda para realizar um filme baiano e independente! O curta-metragem O Melhor Dia do Ano.

          p
            | Na história acompanhamos Leo, um garoto de 16 anos recém-completados, na manhã do seu aniversário. Seus pais, um casal divorciado de meia idade, juntam-se para bater um pequeno parabéns em comemoração ao dia do filho. No entanto, em meio a assuntos mal resolvidos e antigos ressentimentos, acabam discutindo, sabotando o aniversário do garoto.

          p
            | O Curta-metragem terá algo próximo de 17 minutos

          p
            | A história destaca alguns problemas de uma parcela da população brasileira; Falta de comunicação entre pais e filhos, dificuldade em lidar com o divórcio dos pais, introspecção e a constante opção desses jovens em desligar-se da realidade que vivem são problemas que vemos no dia a dia da relação entre os filhos e seus pais, e que constantemente não são tratados ou são abordados de maneira superficial ou não verdadeira.

          p
            | Bem, até aqui vocês devem estar pensando: "quem são as pessoas que estão me pedindo esse dinheiro?", e é importante que vocês conheçam, então, a equipe responsável por fazer O Melhor Dia do Ano acontecer.
      div class="project-rewards"
        - 3.times
          div class="reward"
            a href="#"
              div class="reward-info"
                h2 Pledge $10 or more
                p class="badge"
                  span
                  | 2 backers
                div class="reward-description"
                  p
                    | Reward description lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum
                div class="reward-extra-info"
                  p class="pledge-estimated"
                    | Estimated-delivery
                  p class="pledge-estimated-data"
                    | May 2016

    div id="updates" class="tabs hide"
      ul
        li
          div
            h1 Update
            | updates updates updates
        li
          div
            h1 Update
            | updates updates updates
        li
          div
            h1 Update
            | updates updates updates
        li
          div
            h1 Update
            | updates updates updates
        li
          div
            h1 Update
            | updates updates updates
        li
          div
            h1 Update
            | updates updates updates





    div id="comments" class="tabs hide"
      h1 Comments
    div id="backers" class="tabs hide"
      h1 Backers

app/views/rewards/_form.html.slim
= form_for @reward do |f|
  p
    = f.label :name
    = f.text_field :name

  p
    = f.label :description
    = f.text_field :description

  p
    = f.label :value
    = f.number_field :value, in: 1.0..1000000.0, step: 0.5

  p
    = f.label :project
    = f.text_field :project_id

  = f.submit
end

app/views/rewards/edit.html.slim
h1 Edit Reward

= render 'form'

app/views/rewards/index.html.slim
h1 Projects Rewards

= link_to 'New Reward', new_reward_path

- if @rewards
  - @rewards.each do |reward|
    p
      = reward.name
      = reward.value
      = reward.project_id
      = link_to 'More', reward_path(reward)
  end
end

app/views/rewards/new.html.slim
h1 New Reward

= render 'form'

app/views/rewards/show.html.slim
p
  = @reward.name
  = @reward.value

= link_to 'Edit', edit_reward_path(@reward)
= link_to 'Rewards', rewards_path